#!/bin/bash

set -e

NAME=
VERSION=$(date +%Y%m%d)
RELEASE=1

REGISTRY=gcr.io
REPO=jarvice

PUSH_LATEST=
PUSH_MANIFEST=
PLATFORMS="linux/amd64,linux/ppc64le,linux/arm64"

BUILDER=multiarch
DOCKERFILE=Dockerfile

OUTPUT=

ARCH=$(arch)
[ "$ARCH" = "x86_64" ] && ARCH=amd64

function print_usage {
    cat <<EOF
Usage:
  $0 --name <image-name> [options]

Options:
  --name <image-name>           Name of the image to build (required)
  --version <image-version>     Version number/string to use in the image tag
                                (default: $VERSION)
  --release <image-release>     Release number/string to use in the image tag
                                (default: $RELEASE)
  --registry <registry-name>    Registry to push to
                                (default: $REGISTRY)
  --repo <repository-name>      Specific registry repository to push to
  --platforms                   Platforms to build
                                (default: "$PLATFORMS")
  --push-manifest               Push multiarch manifest
  --push-latest                 Create and push "latest" image tag
  --builder                     Docker buildx builder to use
                                (default: $BUILDER)
  --dockerfile                  Dockerfile to use for docker build
                                (default: $DOCKERFILE)

Example (build image and create/push latest tag):
\$ $0 --name <image-name> --push-latest

Example (build image and multiarch manifest, create/push latest tags):
\$ $0 --name <image-name> --push-latest --push-manifest
EOF
}

while [ $# -gt 0 ]; do
    case $1 in
        --help)
            echo_usage
            exit 0
            ;;
        --name)
            NAME=$2
            shift; shift;
            ;;
        --registry)
            REGISTRY=$2
            shift; shift;
            ;;
        --repo)
            REPO=$2
            shift; shift;
            ;;
        --version)
            VERSION=$2
            shift; shift;
            ;;
        --release)
            RELEASE=$2
            shift; shift;
            ;;
        --push-latest)
            PUSH_LATEST=1
            shift;
            ;;
        --push-manifest)
            PUSH_MANIFEST=--push
            shift;
            ;;
        --platforms)
            PLATFORMS=$2
            shift; shift;
            ;;
        --builder)
            BUILDER=$2
            shift; shift;
            ;;
        --dockerfile)
            DOCKERFILE=$2
            shift; shift;
            ;;
        *)
            print_usage
            exit 1
            ;;
    esac
done

[ -z "$NAME" ] && print_usage && exit 1

IMAGE_BASE=$REPO/$NAME
[ -n "$REGISTRY" ] && IMAGE_BASE=$REGISTRY/$IMAGE_BASE
IMAGE_TAG=$VERSION-$RELEASE

IMAGE=$IMAGE_BASE:$IMAGE_TAG
IMAGE_LATEST=$IMAGE_BASE:latest

export DOCKER_CLI_EXPERIMENTAL=enabled

echo; echo "*** Building image $IMAGE from $DOCKERFILE..."
docker buildx build --rm -t $IMAGE --builder $BUILDER --platform $PLATFORMS $PUSH_MANIFEST -f $DOCKERFILE .

if [ -n "$PUSH_LATEST" ]; then
    echo; echo "*** Pusing image $IMAGE_LATEST..."
    docker buildx build --rm -t $IMAGE_LATEST --builder $BUILDER --platform $PLATFORMS --push -f $DOCKERFILE .
fi

